import { readFile, writeFile } from "fs/promises";

const MAX_STATIC_RULES = 30000;

// Read rules generated by the pipeline
const networkRules = JSON.parse(
  await readFile("output/network-rules.json", "utf-8"),
);

// Convert each rule to DNR format
const dnrRules = [];
let id = 1;

for (const rule of networkRules) {
  if (id > MAX_STATIC_RULES) break;

  // Extract pattern and modifiers
  const dollarIdx = rule.indexOf("$");
  const pattern = dollarIdx !== -1 ? rule.slice(0, dollarIdx) : rule;
  const modifiers =
    dollarIdx !== -1 ? rule.slice(dollarIdx + 1).split(",") : [];

  // Skip non-convertible modifiers
  const nonConvertible = [
    "redirect",
    "csp",
    "replace",
    "hls",
    "jsonprune",
    "xmlprune",
    "permissions",
    "removeheader",
    "urltransform",
  ];
  if (modifiers.some((m) => nonConvertible.includes(m))) continue;

  // Resource types
  const resourceTypeMap = {
    script: "script",
    image: "image",
    stylesheet: "stylesheet",
    xmlhttprequest: "xmlhttprequest",
    sub_frame: "sub_frame",
    font: "font",
    media: "media",
    websocket: "websocket",
  };
  const specifiedTypes = modifiers.filter((m) => resourceTypeMap[m]);
  const resourceTypes =
    specifiedTypes.length > 0
      ? specifiedTypes.map((m) => resourceTypeMap[m])
      : [
          "script",
          "image",
          "xmlhttprequest",
          "sub_frame",
          "stylesheet",
          "font",
          "media",
          "websocket",
          "other",
        ];

  // Handle exceptions BEFORE checking pattern format
  if (pattern.startsWith("@@")) {
    const exceptionPattern = pattern.slice(2);

    // Skip exceptions with empty pattern
    if (exceptionPattern.trim() === "") continue;

    // Skip exceptions with wildcard in domain
    if (exceptionPattern.match(/^\|\|\*/)) continue;

    dnrRules.push({
      id,
      priority: 2,
      action: { type: "allow" },
      condition: { urlFilter: exceptionPattern, resourceTypes },
    });
    id++;
    continue;
  }

  // Skip rules that are not ||domain^ pattern
  if (!pattern.match(/^\|\|[a-z0-9.-]+\^$/)) continue;

  dnrRules.push({
    id,
    priority: 1,
    action: { type: "block" },
    condition: { urlFilter: pattern, resourceTypes },
  });

  id++;
}

// Write to extension/rules.json
await writeFile("extension/rules.json", JSON.stringify(dnrRules, null, 2));

console.log(`Rules converted: ${dnrRules.length} / ${networkRules.length}`);
console.log(`Output: extension/rules.json`);
