import { readFile } from "fs/promises";

// Load rules generated by the pipeline
const networkRules = JSON.parse(
  await readFile("output/network-rules.json", "utf-8"),
);

// Extract the shortcut from a rule
// "||doubleclick.net^" → "doubleclick"
// "||ads.example.com^" → "ads"
function extractShortcut(rule) {
  const match = rule.match(/^\|\|([a-z0-9.-]+)\^/);
  if (!match) return null;
  return match[1].split(".")[0]; // first part of the domain
}

// Build the lookup table: shortcut → [rules]
const lookupTable = {};

for (const rule of networkRules) {
  const shortcut = extractShortcut(rule);
  if (!shortcut) continue;
  if (!lookupTable[shortcut]) lookupTable[shortcut] = [];
  lookupTable[shortcut].push(rule);
}

console.log(`Engine loaded with ${networkRules.length} rules`);
console.log(`Indexed shortcuts: ${Object.keys(lookupTable).length}`);

// Given a URL, find if any rule blocks it
function matchRequest(url, resourceType) {
  const hostname = new URL(url).hostname.toLowerCase(); // "ads.doubleclick.net"
  const parts = hostname.split("."); // ["ads", "doubleclick", "net"]

  for (const part of parts) {
    const candidates = lookupTable[part];
    if (!candidates) continue;

    for (const rule of candidates) {
      // Extract the domain from the rule and check if it matches the URL
      const match = rule.match(/^\|\|([a-z0-9.-]+)\^/);
      if (!match) continue;
      const domain = match[1].toLowerCase();
      if (hostname === domain || hostname.endsWith("." + domain)) {
        // Split rule into pattern and modifiers
        const dollarIdx = rule.indexOf("$");

        // No modifiers → applies to everything → blocked
        if (dollarIdx === -1) return rule;

        // Has modifiers → check if resourceType matches
        const modifiers = rule.slice(dollarIdx + 1).split(",");

        if (modifiers.includes(resourceType)) return rule;
      }
    }
  }

  return null; // not blocked
}

const testUrls = [
  { url: "https://doubleclick.com/ads/track.js", type: "script" },
  { url: "https://ads.doubleclick.com/pixel.gif", type: "image" },

  { url: "https://doubleclick.net/ads/track.js", type: "script" },
  { url: "https://doubleclick.net/popup", type: "popup" },

  { url: "https://google.com/search?q=hello", type: "script" },
  { url: "https://github.com", type: "script" },
];

console.log("\n=== Matching test ===");
for (const { url, type } of testUrls) {
  const rule = matchRequest(url, type);
  if (rule) {
    console.log(`BLOCKED  [${type}] ${url}`);
    console.log(`         → ${rule}`);
  } else {
    console.log(`allowed  [${type}] ${url}`);
  }
}
